Added test cases for lisp extension format
Autodesk-AutoCAD/AutoLispExt pull request #118
Opened 2021-04-02 15:50 UTC by nigma456

##### Objective
Most complex part of the lisp extension work is formatting so we want to add more and more test cases to avoid regressions.
##### Abstractions
In this submission I have added some test cases to cover the lisp extension formatting feature.
1. The lisp extension format has 4 settings which exposed to users in the vscode setting for extension.
format.CloseParenthesisStyle : 'Same line' | 'New line with outer identation'
format.MaxLineChars || 85
format.LongListFormatStyle : 'Single Column' | 'Fill to Margin'
format.NarrowStyleIndent || 2
we tested the formatting by assigning different value for these settings.

2. To get and set values for these setting there are two ways to do.
One way is to read the configuration of these setting by following methods:
let configuration = vscode.workspace.getConfiguration('autolispext');
let formatConfigure = configuration.get('format');
then 
vscode.workspace.getConfiguration('autolispext').update('format.LongListFormatStyle','Single Column');
But it needs to either relaunch the vscode or wait several seconds until it can take effect, so this is not pratical for our 
test.
The other way is to directly change the value by adding some functions exposed from the formatting code.
like 
export function resetMaxLineChars() {
    gMaxLineChars = 80;
    gHasMaxLineChars = false;
}
This is the way we used in our test cases.

3. All the 16 test cases covered various senarios that I can image, may need to add more cases in the future.

##### Tests performed
Pass local test and CI on Github

##### Screen shot

2021-04-05 13:35 UTC, Sen-real requested changes

2021-04-05 13:35 UTC, Sen-real commented on extension/src/format/sexpression.ts
> +let gHasMaxLineChars = false;
This is test case only. Can we avoid doing it in feature code?

2021-04-05 13:35 UTC, Sen-real commented on extension/src/format/sexpression.ts
> -  export function longListFormatAsSingleColum() {
Let's not format the entire file in a PR that contains real code changes. It takes extra time to review things that are not really changed.
If the formatting is wrong, we can submit the test case change first, then create another PR which is purely for code format.

2021-04-05 13:35 UTC, Sen-real commented on extension/src/format/sexpression.ts
> +        if (!gHasMaxLineChars) {
I don't know if this change is correct or not, it seems that when running this method in product, the flag is false, and then the original code that Hualin wrote won't run? is my understanding correct?
Anyway, I suggest not to change feature logic like this only for adding test cases. 
If it's really hard to test against sth. without changing the logic, we can do it via. E2E.

2021-04-05 13:35 UTC, Sen-real commented on extension/src/format/sexpression.ts
> +        if (!gHasIndentSpaces) {
same as above

2021-04-05 13:35 UTC, Sen-real commented on extension/src/format/sexpression.ts
> +        if (!gHasClosedParenInSameLine) {
same as above

2021-04-06 09:22 UTC, nigma456 commented
Close this PR and created a new PR
https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/121

2021-04-06 09:22 UTC, closed without merging